window.livro = {
  portugues: `
    <h2>Capítulo 1 - A Jornada do Tempo</h2>
    <p>Em um pequeno vilarejo escondido entre as montanhas do norte, vivia um velho relojoeiro chamado Elías. Seus dedos enrugados ainda manejavam com precisão engrenagens minúsculas e parafusos delicados. Havia um rumor antigo de que seu relógio de bolso não apenas marcava o tempo, mas também podia dobrá-lo. As pessoas diziam que quem escutasse seus tiques e taques por tempo suficiente conseguiria ouvir vozes do passado.</p>
    <p>Certa manhã, Elías recebeu a visita de uma menina curiosa chamada Aurora. Ela tinha olhos grandes, cheios de perguntas, e cabelos tão dourados quanto o sol da manhã. “É verdade que seu relógio pode nos levar ao passado?”, ela perguntou. Elías sorriu, mas não respondeu. Em vez disso, entregou-lhe um papel antigo, cheio de símbolos estranhos e anotações a lápis.</p>
    <p>Esse era o início de uma jornada que cruzaria os limites da lógica, do espaço e do tempo. Aurora e Elías embarcaram numa aventura através dos séculos, revivendo histórias esquecidas, presenciando batalhas antigas, descobrindo o nascimento de civilizações e testemunhando segredos enterrados sob camadas de silêncio.</p>
    <p>Cada novo destino era desbloqueado quando Aurora decifrava um símbolo do mapa. A cada viagem, o relógio de Elías ficava mais leve, como se cada segredo revelado o libertasse de uma maldição antiga. Eles visitaram bibliotecas em Alexandria, enfrentaram tempestades no mar com navegadores portugueses, e até conversaram com inventores em Florença.</p>
    <p>No entanto, a cada salto no tempo, as consequências começavam a se acumular. Fragmentos do passado se misturavam ao presente. Pessoas esquecidas apareciam em cidades modernas, monumentos desapareciam de registros históricos. O tempo estava se desfiando.</p>
    <p>Em uma noite particularmente silenciosa, Aurora confrontou Elías. “Você sabia o que estava fazendo esse tempo todo?”, ela perguntou. Ele apenas assentiu. “Então por que não parou?” Elías encarou o relógio. “Porque o tempo, minha querida, não é algo que se para. Ele apenas muda de forma.”</p>
    <p>Ao final da jornada, Aurora se viu sozinha com o relógio em mãos. Elías havia desaparecido em um tempo que ninguém conseguia alcançar. Ela sabia que agora era a guardiã do tempo — com o poder de preservá-lo, protegê-lo ou corrompê-lo.</p>
    <p>E assim, em meio às páginas da história, escondida nas dobras do tempo, Aurora caminha. Cada passo é uma lembrança. Cada batida do relógio, um eco da eternidade.</p>
  `,
  ingles: `
    <h2>Chapter 1 - The Journey Through Time</h2>
    <p>In a small village tucked between the northern mountains, lived an old watchmaker named Elías. His wrinkled fingers still handled tiny gears and delicate screws with precision. There was an old rumor that his pocket watch not only told time but could also bend it. People whispered that if you listened to its ticks long enough, you could hear voices from the past.</p>
    <p>One morning, Elías was visited by a curious girl named Aurora. Her eyes were large, full of questions, and her hair as golden as the morning sun. “Is it true your watch can take us to the past?” she asked. Elías smiled, but didn’t answer. Instead, he handed her an old paper filled with strange symbols and pencil notes.</p>
    <p>This marked the beginning of a journey that would cross the limits of logic, space, and time. Aurora and Elías embarked on an adventure through the centuries, reliving forgotten stories, witnessing ancient battles, discovering the birth of civilizations, and uncovering secrets buried under layers of silence.</p>
    <p>Each new destination was unlocked when Aurora deciphered a symbol from the map. With every trip, Elías’s watch became lighter, as if each revealed secret freed it from an ancient curse. They visited libraries in Alexandria, braved storms at sea with Portuguese sailors, and even spoke with inventors in Florence.</p>
    <p>However, with every leap in time, consequences began to pile up. Fragments of the past mixed with the present. Forgotten people appeared in modern cities. Monuments vanished from historical records. Time was unraveling.</p>
    <p>On a particularly silent night, Aurora confronted Elías. “You knew what you were doing all along?” she asked. He merely nodded. “Then why didn’t you stop?” Elías stared at the watch. “Because time, my dear, is not something you stop. It simply changes shape.”</p>
    <p>At the end of the journey, Aurora found herself alone with the watch in her hands. Elías had vanished into a time no one could reach. She knew she was now the guardian of time — with the power to preserve it, protect it, or corrupt it.</p>
    <p>And so, hidden within the folds of time, walking between the pages of history, Aurora moves forward. Each step a memory. Each tick of the watch, an echo of eternity.</p>
  `
}